FROM python:latest

WORKDIR /app

RUN mkdir -p /app  # Ensure /app exists

COPY requirements requirements

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6 libgl1 mesa-utils -y
RUN pip install --no-cache-dir -r requirements

COPY . /app